config/routes.rb
FinalProject::Application.routes.draw do
  
  resources :artists

  root :to => "artists#index"
  
  match "/artists" => "artists#index"
  match "/artists/:id" => "artists#show"
  match "/contact" => "contacts#index"
  match "/about" => "abouts#index"
  match "/records" => "records#index"
  match "/records/:id" => "records#show"
  match "/search_results" => "records#search_results"
  match "/register" => "customers#new"
  match "/login_form" => "customers#login_form"
  match "/login" => "customers#login"
  match "/logout" => "customers#logout"
  match "/buy_now" => "orders#buy_now"
  match "/checkout_one" => "orders#checkout_one"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :cart_items
  resources :customers
  resources :line_items

  resources :orders

end

app/models/about.rb
class About < ActiveRecord::Base
  validates_presence_of :content
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :records
  validates_presence_of :name, :bio, :image
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :customer
  belongs_to :record
  validates_presence_of :customer_id, :record_id, :quantity
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :title, :name, :phone, :address, :email
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  has_many :orders
  has_many :cart_items
  validates_presence_of :first_name, :province_id, :last_name, :city, :address, :postal_code, :phone, :email, :password
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :record
  belongs_to :order
  validates_presence_of :record_id, :order_id, :quantity
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  has_many :records, :through => :line_items
  belongs_to :customer
  validates_presence_of :customer_id, :status
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
  validates_presence_of :name, :gst, :pst, :hst
end

app/models/record.rb
class Record < ActiveRecord::Base
  has_many :line_items
  has_many :cart_items
  belongs_to :artist
  validates_presence_of :artist_id, :name, :price, :image
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    "styles.css", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="head">
    <%= image_tag "grey.png", :id => "logo", :alt => "logo" %>
    <%= image_tag "engraved.png", :id => "name", :alt => "boranarecords" %>
    <hr id="headrule" />
    <nav id="headnav">
      <ul>
	<li><%= link_to "HOME", "/" %></li>
	<li><%= link_to "ARTISTS", "/artists" %></li>
	<li><%= link_to "RECORDS", "/records" %></li>
	<li><%= link_to "ABOUT", "/about" %></li>
	<li><%= link_to "CONTACT", "/contact" %></li>
      </ul>
    </nav>
  </header>
  <div id="right">
    
    <div id="tracks">
      <h1>PLAYLIST</h1>
      <iframe width="100%" height="65" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F1771151&amp;color=a4a4a4&amp;auto_play=false&amp;show_artwork=false"></iframe>
    </div>
    
    <div id="contact">
	<h1>FIND US</h1>
	<nav id="buttons">
	  <ul id="buttonnav">
	    <li><%= link_to(image_tag("buttons/fb.png", :alt => "facebook"), "http://www.facebook.com") %></li>
	    <li><%= link_to(image_tag("buttons/tw.png", :alt => "twitter"), "http://www.twitter.com") %></li>
	    <li><%= link_to(image_tag("buttons/sc.png", :alt => "soundcloud"), "http://www.soundcloud.com") %></li>
	  </ul>
	</nav>
    </div>
    
  </div>
  <div id="content">

<%= yield %>

  </div>
  <div class="search">
    <%= form_tag(search_results_path) do %>
      <%= label_tag(:keywords, "Search Records:") %>
      <%= text_field_tag(:keywords) %>
    <% end %>
  </div>
  
  <div class="login">
  <% if session[:user_id] %>
    Welcome, <%= Customer.where("id = #{session[:user_id]}").first.first_name %>  -  <%= link_to "SHOPPING CART", "/cart_items" %> / <%= link_to "LOG OUT", "/logout" %>
  <% else %>
    <%= link_to "Login", "/login_form" %> / <%= link_to "Register", "/register" %>
  <% end %>
  </div>

</body>
</html>